import siteV3 from './site-v3';

export const config = { runtime: 'edge' };

function replaceMain(html: string, content: string) {
  const start = html.indexOf('<main>');
  const end = html.indexOf('</main>');
  if (start < 0 || end < 0) return html;
  return html.slice(0, start) + `<main>${content}</main>` + html.slice(end + 7);
}

function replaceMany(input: string, pairs: [string, string][]) {
  return pairs.reduce((result, [from, to]) => result.replaceAll(from, to), input);
}

function sharedCopy(html: string) {
  return replaceMany(html, [
    ['WITH. is building shared safety infrastructure around women in South Africa, connecting personal protection, staffed places, responders and organisations before, during and after danger.', 'WITH. is a South African personal safety network built around one idea: people should not have to coordinate every part of their own safety alone.'],
    ['WITH. is building a stronger safety network around women. Join the launch.', 'WITH. is launching soon. Join the network.'],
    ['Join the launch', 'Join the network'],
    ['Help build the network', 'Strengthen the network'],
    ['WITH. is building a South African safety network around the idea that safety should start before the emergency. Live emergency coverage is not active yet. WITH. is not a substitute for SAPS, EMS or other emergency services.', 'WITH. is launching as a personal safety network. Live emergency coverage is not active yet. WITH. is not a substitute for SAPS, EMS or other emergency services.'],
    ['Learn how protection, Assistance Points, response and partnerships are designed to work. Ask WITH. cannot dispatch emergency help.', 'Ask how Guardian, Assistance Points, Trusted Circles and the wider network are designed to work. Ask WITH. cannot dispatch emergency help.'],
  ]);
}

function home() {
  return `<section class="hero homeHero"><div class="wrap heroGrid"><div><div class="ey">Personal safety network · launching in South Africa</div><h1>Safety should start before the emergency.</h1><p class="lead">WITH. helps you start protection for a journey or vulnerable moment, then carries the routine coordination around it — checking what changed, keeping the right context and connecting people or help when they are actually needed.</p><div class="actions"><a class="btn" href="/join">Join the network</a><a class="btn alt" href="/how-it-works">See how it works</a></div><p class="micro"><b>Launching responsibly.</b> Live emergency coverage is not active yet. WITH. does not replace SAPS, EMS or other emergency services.</p></div><figure class="photo"><img src="https://images.unsplash.com/photo-1683110534724-42b900154a34?auto=format&fit=crop&w=1600&q=82" alt="Two women walking together"><figcaption class="photoCopy"><strong>Ordinary movement should not require constant coordination.</strong><br>Start the moment. Let the system carry more of the routine work.</figcaption></figure></div></section>

<section class="storyBand soft"><div class="wrap"><div class="storyIntro"><div><span class="visualLabel"><i data-lucide="circle-help"></i> The problem</span><h2>People are expected to coordinate too much of their own safety.</h2></div><p>A friend on WhatsApp. A security app. A petrol station. A campus desk. Emergency services. A family member. These can all help — but the person often has to remember what to use, when to use it and who to contact while already stressed.</p></div><div class="systemCompare"><article class="systemPanel"><h3>Today</h3><div class="systemNodes"><div class="systemNode"><i data-lucide="smartphone"></i>Open the right app</div><div class="systemNode"><i data-lucide="message-circle"></i>Message someone</div><div class="systemNode"><i data-lucide="map-pin"></i>Find somewhere to go</div><div class="systemNode"><i data-lucide="radio"></i>Work out who can respond</div></div></article><div class="systemBridge"><span>→</span></div><article class="systemPanel connected"><h3>WITH.</h3><div class="systemNodes"><div class="systemNode"><i data-lucide="navigation"></i>Start protection</div><div class="systemNode"><i data-lucide="timer"></i>Routine checks happen automatically</div><div class="systemNode"><i data-lucide="users"></i>Chosen people connect when needed</div><div class="systemNode"><i data-lucide="waypoints"></i>Help paths become clearer</div></div></article></div></div></section>

<section class="storyBand"><div class="wrap"><div class="storyIntro"><div><span class="visualLabel"><i data-lucide="workflow"></i> The solution</span><h2>Start once. Let simple automation carry the routine steps.</h2></div><p>WITH. does not need AI to guess that danger is happening. Most of the useful work can come from reliable timers, state changes, check-ins, retries and clear escalation rules.</p></div><div class="diagramFlow"><article class="diagramNode"><span class="diagramStep">01</span><span class="diagramIcon"><i data-lucide="navigation"></i></span><h3>Start</h3><p>Choose a journey, Countdown or another protected moment.</p><span class="diagramArrow">→</span></article><article class="diagramNode"><span class="diagramStep">02</span><span class="diagramIcon"><i data-lucide="activity"></i></span><h3>Watch the state</h3><p>The app keeps track of the expected moment, connection and simple rules.</p><span class="diagramArrow">→</span></article><article class="diagramNode"><span class="diagramStep">03</span><span class="diagramIcon"><i data-lucide="message-circle-question"></i></span><h3>Check</h3><p>If something meaningful changes, WITH. asks before treating normal life like an emergency.</p><span class="diagramArrow">→</span></article><article class="diagramNode"><span class="diagramStep">04</span><span class="diagramIcon"><i data-lucide="waypoints"></i></span><h3>Connect</h3><p>Trusted people, staffed help or professional response can join the process when the state requires it.</p></article></div><p class="diagramNote"><i data-lucide="info"></i><span>WITH. is designed to reduce coordination, not to predict assault or guarantee that an incident will not happen.</span></p></div></section>

<section class="storyBand dark"><div class="wrap"><div class="storyIntro"><div><span class="visualLabel"><i data-lucide="users-round"></i> The network</span><h2>You are not only using WITH. You are part of the network.</h2></div><p>More people standing together matters. A new person can bring trusted people, participate in pilots, identify gaps and help create demand for better infrastructure. But downloads alone are not physical coverage.</p></div><div class="roleGrid"><article class="roleCard"><i data-lucide="user-round-check"></i><h3>People</h3><p>Start protection, build Trusted Circles, participate and invite others into the network.</p><strong>Make the network human</strong></article><article class="roleCard"><i data-lucide="store"></i><h3>Places</h3><p>Businesses and institutions can provide staffed places with a real receiving process.</p><strong>Add physical coverage</strong></article><article class="roleCard"><i data-lucide="radio"></i><h3>Responders</h3><p>Security and emergency partners can connect real response capacity where agreements exist.</p><strong>Add response capacity</strong></article><article class="roleCard"><i data-lucide="building-2"></i><h3>Organisations</h3><p>Employers, campuses, banks, insurers and property groups can fund, distribute or contribute infrastructure.</p><strong>Help the network scale</strong></article><article class="roleCard"><i data-lucide="heart-handshake"></i><h3>NGOs</h3><p>Specialist organisations can strengthen prevention, survivor support and recovery pathways.</p><strong>Bring expertise</strong></article><article class="roleCard"><i data-lucide="landmark"></i><h3>Public services</h3><p>Government participation can connect facilities, programmes and emergency infrastructure over time.</p><strong>Connect public capacity</strong></article></div></div></section>

<section class="storyBand soft"><div class="wrap split"><div><div class="ey">An honest network effect</div><h2>More people can help the network grow. More infrastructure makes it stronger.</h2></div><div class="copy"><p>WITH. will not claim that another download automatically makes everyone safer. The useful network effect comes when participation leads to more trusted support, more staffed Assistance Points, stronger response partnerships and better local coverage.</p><p><b>People create momentum. Places and responders create coverage.</b></p></div></div></section>

<section><div class="wrap cta"><div class="split"><div><div class="ey">Stand with the network</div><h2>There is more than one way to contribute.</h2><p>Use WITH. Join a pilot. Bring people you trust. Offer a staffed location. Connect response capacity. Sponsor a community. Bring specialist support.</p></div><div><a class="btn" href="/join">Join the network</a><br><br><a class="btn alt" href="/organisations">Strengthen the network</a></div></div></div></section>`;
}

function mission() {
  return `<section class="pageHero"><div class="wrap"><div class="crumb"><a href="/">WITH.</a> / Mission</div><div class="ey">Why WITH.</div><h1>Women should not have to become security experts to move through ordinary life.</h1><p class="lead">WITH. exists to move more of the coordination burden away from the person and into a network that can prepare, check, connect and continue when something changes.</p></div></section>
<section class="storyBand"><div class="wrap split"><div><div class="ey">The burden today</div><h2>Too much depends on remembering the right thing at the worst time.</h2></div><div class="copy"><p>Share a location. Tell a friend. Check the route. Save a security number. Find somewhere open. Work out whether anyone saw the message.</p><p>Those are reasonable individual actions. They should not be the entire safety infrastructure.</p></div></div></section>
<section class="dark"><div class="wrap"><div class="ey" style="color:var(--lime)">The belief</div><p class="quote">Safety should exist around the person, not only inside the phone in her hand.</p></div></section>
<section class="storyBand soft"><div class="wrap"><div class="storyIntro"><div><span class="visualLabel"><i data-lucide="network"></i> Shared safety infrastructure</span><h2>Different participants can carry different parts.</h2></div><p>WITH. does not need to own every piece. It needs to make the handoffs between the pieces more useful.</p></div><div class="diagramFlow"><article class="diagramNode"><span class="diagramIcon"><i data-lucide="users"></i></span><h3>People</h3><p>Chosen human support and community participation.</p></article><article class="diagramNode"><span class="diagramIcon"><i data-lucide="store"></i></span><h3>Places</h3><p>Staffed locations that know how to receive someone.</p></article><article class="diagramNode"><span class="diagramIcon"><i data-lucide="radio"></i></span><h3>Response</h3><p>Professional and public response where it is actually available.</p></article><article class="diagramNode"><span class="diagramIcon"><i data-lucide="heart-handshake"></i></span><h3>Support</h3><p>Prevention, recovery and specialist GBV services delivered with credible partners.</p></article></div></div></section>
<section><div class="wrap cta"><div class="split"><div><div class="ey">The mission in one line</div><h2>Make safety easier to start and harder to lose when one part fails.</h2></div><div><a class="btn" href="/how-it-works">See how it works</a></div></div></div></section>`;
}

function how() {
  return `<section class="pageHero"><div class="wrap"><div class="crumb"><a href="/">WITH.</a> / How it works</div><div class="ey">Simple on the surface</div><h1>The system should think through the routine steps so you do not have to.</h1><p class="lead">WITH. uses explicit states, timers, check-ins and fallback rules. AI is not required to decide whether you are in danger.</p></div></section>
<section class="storyBand"><div class="wrap"><div class="storyIntro"><div><span class="visualLabel"><i data-lucide="layers-3"></i> Start with the moment</span><h2>Three simple ways in.</h2></div><p>The user chooses the moment. Automation carries the routine coordination after that choice.</p></div><div class="roleGrid"><article class="roleCard"><i data-lucide="sun"></i><h3>Everyday</h3><p>Check readiness and know what support is available before protection starts.</p><strong>Sharing off by default</strong></article><article class="roleCard"><i data-lucide="navigation"></i><h3>Guardian</h3><p>Protect a journey from A to B and notice when the expected pattern meaningfully changes.</p><strong>Active for the chosen journey</strong></article><article class="roleCard"><i data-lucide="timer"></i><h3>Safety Countdown</h3><p>Protect a short vulnerable moment with a timer and a simple confirmation at the end.</p><strong>Active for the chosen time</strong></article></div></div></section>
<section class="storyBand soft"><div class="wrap"><div class="storyIntro"><div><span class="visualLabel"><i data-lucide="workflow"></i> What happens automatically</span><h2>Rules first. Human judgement when it matters.</h2></div><p>WITH. should automate facts and deadlines, not invent danger from weak signals.</p></div><div class="journeySteps"><article class="journeyStep"><h3>Preflight</h3><p>Check permissions, connection and available support paths.</p></article><article class="journeyStep"><h3>Run</h3><p>Maintain the timer, expected arrival and connection state.</p></article><article class="journeyStep"><h3>Notice</h3><p>A sustained deviation, expired Countdown or missed milestone can require a check.</p></article><article class="journeyStep"><h3>Ask</h3><p>“Are you okay?” before treating normal variation as an emergency.</p></article><article class="journeyStep"><h3>Escalate</h3><p>Explicit help, duress or an unanswered configured check moves the state forward.</p></article><article class="journeyStep"><h3>Continue</h3><p>Once an incident exists, losing the phone should not erase it.</p></article></div></div></section>
<section class="dark"><div class="wrap split"><div><div class="ey" style="color:var(--lime)">One failure should not end the chain</div><h2>The phone can disappear. The incident should not.</h2></div><div class="copy"><p>The device can continue local logic when data is poor. The backend keeps the latest confirmed shared state. Notification and response work can retry without creating duplicate incidents.</p><p>Professional response is only shown where a real response path has been validated.</p></div></div></section>
<section><div class="wrap cta"><div class="split"><div><div class="ey">The important boundary</div><h2>WITH. checks. People and responders make real-world decisions.</h2><p>A missed heartbeat alone should not be treated as proof of an assault. Explicit SOS, duress and defined escalation rules carry more weight than guesswork.</p></div><div><a class="btn" href="/trust">See the trust model</a></div></div></div></section>`;
}

function assistance() {
  return `<section class="pageHero"><div class="wrap"><div class="crumb"><a href="/">WITH.</a> / Assistance Points</div><div class="ey">Physical help</div><h1>A place that knows how to help.</h1><p class="lead">An Assistance Point is not a permanent “safe place” badge. It is a currently verified staffed location with a simple receiving process and a defined path to further help.</p></div></section>
<section class="storyBand"><div class="wrap"><div class="storyIntro"><div><span class="visualLabel"><i data-lucide="badge-check"></i> Verification that expires</span><h2>Being verified once is not enough.</h2></div><p>Staff change. Hours change. Procedures get forgotten. WITH. should automatically stop presenting a location as currently available when its operational status becomes stale.</p></div><div class="verifyLedger"><div><b>ORGANISATION</b><span>Identity and participation confirmed</span></div><div><b>LOCATION</b><span>Correct place and public-facing entry point</span></div><div><b>STAFFING</b><span>Current operating status, not an old promise</span></div><div><b>PROCEDURE</b><span>Simple receive, acknowledge and escalate steps</span></div><div><b>RE-CHECK</b><span>Verification expires and must be refreshed</span></div></div></div></section>
<section class="storyBand soft"><div class="wrap"><div class="storyIntro"><div><span class="visualLabel"><i data-lucide="door-open"></i> The staff job stays small</span><h2>Receive. Acknowledge. Support. Hand over.</h2></div><p>A business should not have to become a security company to contribute.</p></div><div class="assistFlow"><article class="assistStep"><i><span data-lucide="person-standing"></span></i><h3>Receive</h3><p>Move the person into a visible staffed area.</p></article><article class="assistStep"><i><span data-lucide="badge-check"></span></i><h3>Acknowledge</h3><p>Confirm that the request has been received.</p></article><article class="assistStep"><i><span data-lucide="users-round"></span></i><h3>Support</h3><p>Follow the defined procedure without confrontation or investigation.</p></article><article class="assistStep"><i><span data-lucide="handshake"></span></i><h3>Hand over</h3><p>Connect the appropriate trusted, professional or emergency path.</p></article></div></div></section>
<section class="dark"><div class="wrap"><div class="ey" style="color:var(--lime)">Important</div><h2>The map should prefer honest availability over lots of pins.</h2><p class="copy">One location we know is staffed is more useful than ten locations whose status has not been checked recently.</p></div></section>
<section><div class="wrap cta"><div class="split"><div><div class="ey">Businesses can contribute more than a place</div><h2>A location can become part of a wider community safety contribution.</h2><p>A gym might offer a staffed Assistance Point and partner-led self-defence classes. A campus can connect security and counselling. A retailer can contribute locations. WITH. connects or promotes credible programmes rather than pretending to become every specialist service itself.</p></div><div><a class="btn" href="/join">Offer a location or programme</a></div></div></div></section>`;
}

function organisations() {
  return `<section class="pageHero"><div class="wrap"><div class="crumb"><a href="/">WITH.</a> / Organisations</div><div class="ey">Strengthen the network</div><h1>Bring the piece you already have.</h1><p class="lead">WITH. cannot build better safety infrastructure alone. Businesses, security companies, employers, universities, banks, insurers, property groups, NGOs, government and communities already hold different pieces of the solution.</p><div class="actions"><a class="btn" href="/join">Explore a partnership</a></div></div></section>
<section class="storyBand soft"><div class="wrap"><div class="storyIntro"><div><span class="visualLabel"><i data-lucide="puzzle"></i> Different contributions</span><h2>No partner needs to own the whole solution.</h2></div><p>A useful partnership can contribute money, places, response capacity, distribution, expertise, programmes or public infrastructure.</p></div><div class="roleGrid"><article class="roleCard"><i data-lucide="store"></i><h3>Businesses</h3><p>Suitable locations, venues, programmes or staffed Assistance Points.</p><strong>Add practical coverage</strong></article><article class="roleCard"><i data-lucide="radio"></i><h3>Security providers</h3><p>Control rooms, responders and contracted geographic response capacity.</p><strong>Add response</strong></article><article class="roleCard"><i data-lucide="briefcase-business"></i><h3>Employers</h3><p>Support workforces, late shifts, work travel and local coverage.</p><strong>Support people beyond the office</strong></article><article class="roleCard"><i data-lucide="graduation-cap"></i><h3>Universities</h3><p>Campuses, residences, security, counselling and student communities.</p><strong>Build around students</strong></article><article class="roleCard"><i data-lucide="landmark"></i><h3>Banks & insurers</h3><p>Reach, sponsorship, customer access and large-scale preventative partnerships.</p><strong>Help the network scale</strong></article><article class="roleCard"><i data-lucide="building"></i><h3>Property groups</h3><p>Receptions, security teams, properties and precinct infrastructure.</p><strong>Strengthen local coverage</strong></article><article class="roleCard"><i data-lucide="heart-handshake"></i><h3>NGOs</h3><p>GBV prevention, counselling, shelters, legal pathways and survivor support.</p><strong>Bring specialist expertise</strong></article><article class="roleCard"><i data-lucide="landmark"></i><h3>Government</h3><p>Public facilities, services, programmes and later public-private integrations.</p><strong>Connect public infrastructure</strong></article></div></div></section>
<section class="storyBand"><div class="wrap split"><div><div class="ey">A sustainable business</div><h2>The network has to be commercially strong enough to keep improving.</h2></div><div class="copy"><p>WITH. is being built as a business, not as a promise that good intentions will pay for safety infrastructure. Partnerships should support reliable technology, people, verification, response integrations and geographic expansion.</p><p>As the network grows, WITH. can also partner on more prevention, education and recovery work without trying to become every service itself.</p></div></div></section>
<section class="storyBand dark"><div class="wrap"><div class="storyIntro"><div><span class="visualLabel"><i data-lucide="repeat-2"></i> The partnership flywheel</span><h2>People create momentum. Partners turn momentum into infrastructure.</h2></div><p>The network is strongest when participation produces real-world capacity rather than only more app installs.</p></div><div class="growthFlow"><article class="growthStep active"><strong>01</strong><h3>People join</h3><p>Use protection, invite trusted people and help prove demand.</p></article><article class="growthStep"><strong>02</strong><h3>Places join</h3><p>More staffed Assistance Points and community programmes.</p></article><article class="growthStep"><strong>03</strong><h3>Responders connect</h3><p>More validated response capacity in specific areas.</p></article><article class="growthStep"><strong>04</strong><h3>Organisations participate</h3><p>Funding, distribution and infrastructure support expansion.</p></article><article class="growthStep"><strong>05</strong><h3>WITH. reinvests</h3><p>Improve reliability, coverage, operations and credible community partnerships.</p></article></div></div></section>
<section><div class="wrap cta"><div class="split"><div><div class="ey">Start with one real contribution</div><h2>A location. A fleet. A campus. A programme. A community. A partnership.</h2><p>The first question is not “Which package do you want?” It is “What useful piece of the network can we build together?”</p></div><div><a class="btn" href="/join">Strengthen the network</a></div></div></div></section>`;
}

function trust() {
  return `<section class="pageHero"><div class="wrap"><div class="crumb"><a href="/">WITH.</a> / Trust</div><div class="ey">Safety without surveillance</div><h1>WITH. should understand the protected moment, not build a history of your life.</h1><p class="lead">Protection is designed as a closed-loop event: you start it, the system uses the context needed for that active purpose, and routine sharing ends when the moment closes.</p></div></section>
<section class="storyBand soft"><div class="wrap"><div class="storyIntro"><div><span class="visualLabel"><i data-lucide="repeat-2"></i> Closed-loop protection</span><h2>Start. Protect. Resolve. Close.</h2></div><p>The system needs enough information to carry the active safety process. It does not need to become a permanent whereabouts service.</p></div><div class="diagramFlow"><article class="diagramNode"><span class="diagramStep">01</span><span class="diagramIcon"><i data-lucide="play"></i></span><h3>Start</h3><p>You choose the journey or vulnerable moment.</p><span class="diagramArrow">→</span></article><article class="diagramNode"><span class="diagramStep">02</span><span class="diagramIcon"><i data-lucide="navigation"></i></span><h3>Protect</h3><p>Only the context needed for the active session is used.</p><span class="diagramArrow">→</span></article><article class="diagramNode"><span class="diagramStep">03</span><span class="diagramIcon"><i data-lucide="badge-check"></i></span><h3>Resolve</h3><p>Arrive safely or complete the incident/support process.</p><span class="diagramArrow">→</span></article><article class="diagramNode"><span class="diagramStep">04</span><span class="diagramIcon"><i data-lucide="circle-stop"></i></span><h3>Close</h3><p>Routine protection and routine sharing end with the event.</p></article></div></div></section>
<section class="storyBand"><div class="wrap trustPair"><div class="never"><div class="ey">WITH. will not be built for</div><h3>Permanent surveillance.</h3><p>No public map of nearby women. No secret partner tracking. No sale of individual movement histories. No AI pretending to know an assault is happening from a weak signal.</p></div><div class="always"><div class="ey">WITH. is built for</div><h3>Purpose-bound protection.</h3><p>User-started sessions. Minimum necessary context. Explicit Trusted Circle access. Clear incident states. Routine sharing that ends when its purpose ends.</p></div></div></section>
<section class="dark"><div class="wrap split"><div><div class="ey" style="color:var(--lime)">Automation boundary</div><h2>Automation handles facts. It should not invent certainty.</h2></div><div class="copy"><p>Timers can expire. A route can deviate. A check can go unanswered. A notification can fail and retry. Those are facts the system can act on.</p><p>Whether an assault is happening is not something WITH. should claim to know from a generic AI score.</p></div></div></section>`;
}

function join() {
  return `<section class="pageHero"><div class="wrap"><div class="crumb"><a href="/">WITH.</a> / Join</div><div class="ey">Join the network</div><h1>Use WITH. or help strengthen what can exist around it.</h1><p class="lead">People, businesses, responders, institutions, NGOs and public organisations can all contribute differently.</p></div></section>
<section class="storyBand soft"><div class="wrap"><div class="storyIntro"><div><span class="visualLabel"><i data-lucide="users-round"></i> Two simple paths</span><h2>Join as a person. Or bring something the network can use.</h2></div><p>You do not need to be a business to matter, and a business does not need to become a security company to participate.</p></div><div class="trustPair"><div class="always"><div class="ey">For people</div><h3>Join the launch network.</h3><p>Test Guardian and Countdown, build your Trusted Circle, give feedback, join pilots and invite people you trust.</p><a class="btn" href="#join-form">Join as a person</a></div><div class="panel"><div class="ey">For partners</div><h3>Strengthen the network.</h3><p>Offer a location, response capacity, funding, a programme, expertise, distribution, public infrastructure or another useful contribution.</p><a class="btn alt" href="#join-form">Join as a partner</a></div></div></div></section>
<section id="join-form"><div class="wrap"><div class="head"><div><div class="ey">Launch interest</div><h2>Tell us how you want to participate.</h2></div><div class="copy"><p>The existing launch form below records interest only. Joining does not activate live emergency coverage.</p></div></div></div></section>`;
}

export default async function handler(req: Request) {
  const page = new URL(req.url).searchParams.get('page') || 'home';
  const response = await siteV3(req);
  let html = await response.text();
  html = sharedCopy(html);

  if (page === 'home') html = replaceMain(html, home());
  if (page === 'mission') html = replaceMain(html, mission());
  if (page === 'how' || page === 'how-it-works') html = replaceMain(html, how());
  if (page === 'assistance' || page === 'assistance-points') html = replaceMain(html, assistance());
  if (page === 'organisations') html = replaceMain(html, organisations());
  if (page === 'trust') html = replaceMain(html, trust());
  if (page === 'join') {
    const existing = html.slice(html.indexOf('<main>') + 6, html.indexOf('</main>'));
    const formStart = existing.indexOf('<section style="padding-top:20px">');
    const formEnd = formStart >= 0 ? existing.indexOf('</section>', formStart) : -1;
    const formSection = formStart >= 0 && formEnd >= 0 ? existing.slice(formStart, formEnd + 10) : '';
    html = replaceMain(html, join() + formSection);
  }

  return new Response(html, { status: response.status, headers: response.headers });
}
