import siteV2 from './site-v2';

export const config = { runtime: 'edge' };

type Pair = [string, string];

function replaceMany(input: string, pairs: Pair[]) {
  return pairs.reduce((result, [from, to]) => result.replaceAll(from, to), input);
}

function replaceMain(html: string, content: string) {
  const start = html.indexOf('<main>');
  const end = html.indexOf('</main>');
  if (start < 0 || end < 0) return html;
  return html.slice(0, start) + `<main>${content}</main>` + html.slice(end + 7);
}

function publicStory(html: string) {
  return replaceMany(html, [
    ['The goal is to keep core protection at R0 for the individual. Organisation subscriptions help fund the network, coverage, response capacity and broader prevention work.', 'The goal is to keep core protection accessible while partnerships help the wider network grow sustainably.'],
    ['Women can start protection from the first installation. Businesses can add staffed places. Security providers can add response capacity. Organisation subscriptions help fund the network and keep core protection at R0.', 'Women can start protection from the first installation. Businesses can add staffed places. Security providers can add response capacity. Organisations, government and NGOs can help the wider network grow.'],
    ['Organisations can subscribe, contribute infrastructure and connect response capacity so the network can scale.', 'Organisations can contribute infrastructure, response capacity, reach and partnerships so the network can scale.'],
    ['Organisation subscriptions can help keep core protection at R0 and fund network expansion.', 'Organisation participation can help expand physical coverage, response capacity and support around the network.'],
    ['Individuals can help test the experience. Businesses can contribute places. Security companies can contribute response capacity. Organisations can subscribe. Government, NGOs and community organisations can strengthen public, prevention and recovery pathways.', 'Individuals can help test the experience. Businesses can contribute places. Security companies can contribute response capacity. Organisations can contribute funding, reach and infrastructure. Government, NGOs and community organisations can strengthen public, prevention and recovery pathways.'],
  ]);
}

function organisationsPublic() {
  return `<section class="pageHero"><div class="wrap"><div class="crumb"><a href="/">WITH.</a> / Organisations</div><div class="ey">Help build the safety network</div><h1>Help us build better safety infrastructure around women.</h1><p class="lead">WITH. cannot build a meaningful safety network alone. Businesses, security companies, employers, universities, banks, insurers, property groups, NGOs, government and communities already hold different pieces of the solution.</p><div class="actions"><a class="btn" href="/join">Help build the network</a><a class="btn alt" href="#pilot">Explore a pilot</a></div></div></section>

<section class="storyBand"><div class="wrap"><div class="storyIntro"><div><span class="visualLabel"><i data-lucide="circle-help"></i> The problem</span><h2>Women are still expected to coordinate too much of their own safety.</h2></div><p>A phone. A friend. A security company. A staffed business. Emergency services. A support organisation. These resources exist, but they do not always work as one connected system when someone needs them.</p></div><div class="convergeFlow"><div class="fragmentCloud"><div class="fragmentNode"><i data-lucide="smartphone"></i>Phone</div><div class="fragmentNode"><i data-lucide="users"></i>Trusted people</div><div class="fragmentNode"><i data-lucide="store"></i>Businesses</div><div class="fragmentNode"><i data-lucide="radio"></i>Security</div><div class="fragmentNode"><i data-lucide="landmark"></i>Public services</div><div class="fragmentNode"><i data-lucide="heart-handshake"></i>NGOs</div></div><div class="convergeHub"><div><strong>WITH.</strong><span>connect the pieces</span></div></div><div class="supportCloud"><div class="supportNode"><i data-lucide="shield-check"></i>Protection</div><div class="supportNode"><i data-lucide="map-pin"></i>Places to go</div><div class="supportNode"><i data-lucide="siren"></i>Response</div><div class="supportNode"><i data-lucide="heart-handshake"></i>Recovery</div></div></div><p class="diagramNote"><i data-lucide="info"></i><span>WITH. is being built to connect existing capacity and make the handoffs around a protected person clearer.</span></p></div></section>

<section class="storyBand soft"><div class="wrap"><div class="storyIntro"><div><span class="visualLabel"><i data-lucide="network"></i> The solution</span><h2>Build a network around the person, not another isolated safety tool.</h2></div><p>The app starts the protected moment. The wider network can add people, places, professional response, public services and specialist support around it.</p></div><div class="diagramFlow"><article class="diagramNode"><span class="diagramStep">01</span><span class="diagramIcon"><i data-lucide="navigation"></i></span><h3>Protect</h3><p>A woman starts Guardian, a Countdown or another protected moment.</p><span class="diagramArrow">→</span></article><article class="diagramNode"><span class="diagramStep">02</span><span class="diagramIcon"><i data-lucide="users"></i></span><h3>Connect people</h3><p>Trusted people can become part of the active safety process.</p><span class="diagramArrow">→</span></article><article class="diagramNode"><span class="diagramStep">03</span><span class="diagramIcon"><i data-lucide="store"></i></span><h3>Reach places</h3><p>Participating staffed locations can provide practical places to go.</p><span class="diagramArrow">→</span></article><article class="diagramNode"><span class="diagramStep">04</span><span class="diagramIcon"><i data-lucide="radio"></i></span><h3>Reach response</h3><p>Security, emergency and specialist support can connect when the event requires it.</p></article></div></div></section>

<section class="storyBand"><div class="wrap"><div class="storyIntro"><div><span class="visualLabel"><i data-lucide="puzzle"></i> Bring the piece you already have</span><h2>No organisation needs to own the whole solution.</h2></div><p>Different partners can strengthen different parts of the network using infrastructure, reach and expertise they already have.</p></div><div class="roleGrid"><article class="roleCard"><i data-lucide="store"></i><h3>Businesses</h3><p>Contribute suitable staffed locations that could become verified Assistance Points.</p><strong>Add physical coverage</strong></article><article class="roleCard"><i data-lucide="radio"></i><h3>Security companies</h3><p>Connect control rooms, responders and existing response capacity.</p><strong>Strengthen response</strong></article><article class="roleCard"><i data-lucide="briefcase-business"></i><h3>Employers</h3><p>Support employees, workplace corridors and existing company safety infrastructure.</p><strong>Protect beyond the office door</strong></article><article class="roleCard"><i data-lucide="graduation-cap"></i><h3>Universities</h3><p>Connect students, residences, campuses, security and support services.</p><strong>Build around students</strong></article><article class="roleCard"><i data-lucide="building"></i><h3>Property groups</h3><p>Connect receptions, security teams, residents and precinct infrastructure.</p><strong>Strengthen local coverage</strong></article><article class="roleCard"><i data-lucide="landmark"></i><h3>Banks & insurers</h3><p>Use reach, partnerships and resources to support preventative safety at scale.</p><strong>Extend the network</strong></article><article class="roleCard"><i data-lucide="landmark"></i><h3>Government</h3><p>Connect public facilities, emergency services, programmes and public-private pilots.</p><strong>Link public infrastructure</strong></article><article class="roleCard"><i data-lucide="heart-handshake"></i><h3>NGOs & community organisations</h3><p>Bring specialist GBV prevention, survivor support, counselling, shelter and recovery expertise.</p><strong>Extend beyond the incident</strong></article><article class="roleCard"><i data-lucide="waypoints"></i><h3>WITH.</h3><p>Provide the connective technology and operating layer that helps these contributions work together.</p><strong>Connect the pieces</strong></article></div></div></section>

<section class="storyBand soft"><div class="wrap"><div class="storyIntro"><div><span class="visualLabel"><i data-lucide="map"></i> Coverage through partnership</span><h2>Every useful contribution can strengthen the network around women.</h2></div><p>Coverage is not created by app downloads alone. It grows when real places, real response capacity and real support services become connected.</p></div><div class="growthFlow"><article class="growthStep active"><strong>01</strong><h3>Personal protection</h3><p>Women can start a protected journey or vulnerable moment.</p></article><article class="growthStep"><strong>02</strong><h3>More places</h3><p>Businesses and institutions add staffed Assistance Points where appropriate.</p></article><article class="growthStep"><strong>03</strong><h3>More response</h3><p>Security and response partners add professional capacity and clearer handoffs.</p></article><article class="growthStep"><strong>04</strong><h3>More public support</h3><p>Government and public institutions connect relevant services and infrastructure.</p></article><article class="growthStep"><strong>05</strong><h3>More prevention & recovery</h3><p>NGOs and specialist partners strengthen what happens before and after the incident.</p></article></div><p class="diagramNote"><i data-lucide="info"></i><span>Better coverage and response must be proven through real pilots and operating data. The website does not claim live national coverage today.</span></p></div></section>

<section class="storyBand dark"><div class="wrap"><div class="storyIntro"><div><span class="visualLabel"><i data-lucide="radio"></i> Why partnership matters</span><h2>Better coverage. Better handoffs. More response options. Fewer single points of failure.</h2></div><p>South Africa already has significant private, public and community safety capacity. WITH. should help those systems work together more effectively instead of trying to rebuild every piece from zero.</p></div><div class="failureGrid"><article class="failureItem"><b><i data-lucide="store"></i>Places</b><span>More participating staffed locations can mean more practical places to reach help.</span></article><article class="failureItem"><b><i data-lucide="radio"></i>Response</b><span>More response partners can create more resilient coverage and escalation options.</span></article><article class="failureItem"><b><i data-lucide="landmark"></i>Public infrastructure</b><span>Government participation can connect public services, facilities and programmes.</span></article><article class="failureItem"><b><i data-lucide="heart-handshake"></i>Specialist support</b><span>NGOs and GBV organisations can strengthen prevention, survivor support and recovery.</span></article></div></div></section>

<section class="storyBand" id="pilot"><div class="wrap"><div class="storyIntro"><div><span class="visualLabel"><i data-lucide="milestone"></i> Start small</span><h2>Build one part of the network, prove it, then expand.</h2></div><p>A partner does not need to solve the whole country. Start with one office, campus, property, retail group, community, corridor or response area and test whether the model works.</p></div><div class="journeySteps"><article class="journeyStep"><h3>Choose</h3><p>Define the community, location or area.</p></article><article class="journeyStep"><h3>Connect</h3><p>Identify the infrastructure or capacity already available.</p></article><article class="journeyStep"><h3>Pilot</h3><p>Run a focused real-world test.</p></article><article class="journeyStep"><h3>Measure</h3><p>Usage, coverage, handoffs and response outcomes.</p></article><article class="journeyStep"><h3>Improve</h3><p>Fix the gaps the pilot exposes.</p></article><article class="journeyStep"><h3>Expand</h3><p>Grow when the operating model earns it.</p></article></div></div></section>

<section class="storyBand soft"><div class="wrap split"><div><div class="ey">A sustainable network</div><h2>The network has to be able to keep growing.</h2></div><div class="copy"><p>Partnerships should make it possible to maintain the technology, expand useful coverage, connect more response capacity and support more prevention and recovery work over time.</p><p>Specific commercial models are discussed directly with partners rather than explained on the public website.</p></div></div></section>

<section><div class="wrap cta"><div class="split"><div><div class="ey">The invitation</div><h2>What part of the network could you contribute?</h2><p>A location. A security team. A fleet. A campus. A property portfolio. Public infrastructure. Community expertise. Specialist support. Reach. Funding. Technology. Distribution.</p><p>You do not need to own the whole solution. Bring the piece you already have.</p></div><div><a class="btn" href="/join">Help build the network</a></div></div></div></section>`;
}

export default async function handler(req: Request) {
  const page = new URL(req.url).searchParams.get('page') || 'home';
  const response = await siteV2(req);
  let html = await response.text();
  html = publicStory(html);
  if (page === 'organisations') html = replaceMain(html, organisationsPublic());
  return new Response(html, { status: response.status, headers: response.headers });
}
